### ISSUE TITLE
Wrong font in State of CSS 2021 screenshot

### ISSUE THREAD

**Issue by foolip** [StateOfJS/StateOfCSS-homepage#10]
I'm pretty sure this is the wrong repo, but can't find the right repo.

https://stateofx-images.netlify.app/captures/css2021/en-US/grid.png is linked from https://2021.stateofcss.com/en-US/features/layout and looks like this:
![image](https://user-images.githubusercontent.com/498917/146456961-fd01e10c-841c-4866-ac89-835ef357ea66.png)

The font for the title looks like the standard serif font, maybe the webfont for the titles wasn't loaded when this screenshot was taken?

I'm not sure if it affects any other screenshots too.

If this is done with a Puppeteer script or similar, then in addition to waiting for the load event, consider `await document.fonts.ready` before the screenshot. (But start awaiting after the load event. It's complicated.)

**Comment by foolip** [comment]
I noticed this in https://github.com/GoogleChrome/web.dev/pull/7062.

**Comment by SachaG** [comment]
I think this is because I hadn't defined a proper fallback for code, it should be good now. Just need to regenerate everything.
