### ISSUE TITLE
Broken fragment URLs (doesn't scroll to target)

### ISSUE THREAD

**Issue by foolip** [StateOfJS/StateOfCSS-homepage#11]
Links like https://2021.stateofcss.com/en-US/features/layout/#subgrid don't work, don't scroll to the target. The permalinks given on the site are on the form https://2021.stateofcss.com/en-US/features/layout/subgrid but those redirect to the fragment versions.

Note that after loading there is no element on the page with ID "subgrid", so that's the first place to start looking I think.

P.S. Like https://github.com/StateOfJS/StateOfCSS-homepage/issues/10 I'm sure this is in the wrong repo, but don't know what the right one is

**Comment by SachaG** [comment]
Should be fixed.

**Comment by foolip** [comment]
I can confirm, thanks!
