### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by thmsnhl** [StateOfJS/StateOfCSS-homepage#2]
It seems like there are missing translations in the Sign up form and also in the footer.

For example:
`[accounts.please_log_in]` is rendered directly, instead of showing the correct text.

See the screenshot attached below:
![Screenshot_20201026-055058](https://user-images.githubusercontent.com/5750821/97135047-7c49d200-174f-11eb-820a-460ecb753cb4.png)

**Comment by SachaG** [comment]
Sorry our translation API went down for a while, it should be back to normal now :)

**Comment by sentience** [comment]
Looks like #6 is a regression of this.
