### ISSUE TITLE
Login page broken

### ISSUE THREAD

**Issue by davidelrizzo** [StateOfJS/StateOfCSS-homepage#6]
![Capture](https://user-images.githubusercontent.com/1995386/97502711-cccb6480-19c7-11eb-934f-65cc55e8118a.JPG)

Links broken, button broken, text missing. 
Can't figure out how to to login/signup.

**Comment by cmrn** [comment]
I'm also seeing the same issue. It looks like the graphql endpoint which sets the locale is erroring:

```
{
	"errors": [
		{
			"message": "invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"locale"
			],
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"exception": {
					"message": "invalid json response body at http://api.stateofjs.com/graphql reason: Unexpected token < in JSON at position 0",
					"type": "invalid-json"
				}
			}
		}
	],
	"data": {
		"locale": null
	}
}
```

**Comment by SachaG** [comment]
Oh right, I think a recent PR might've broken our translation API…

**Comment by SachaG** [comment]
I keep forgetting that Heroku will deploy broken builds too :( Anyway should be fixed, sorry about that!
